# Generated by Django 4.2.4 on 2023-08-22 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "meal")},
        ),
        migrations.AlterIndexTogether(
            name="rating",
            index_together={("user", "meal")},
        ),
    ]
